### ISSUE TITLE
建议拆分内核

### ISSUE THREAD

**Issue by Chr0nixz** [XiaoYouChR/Ghost-Downloader-3#13]
下载器内核用python实现的话效率还是太低了，哪怕可以nogil，QThread的开销也太大了。
建议换成对并行处理支持更好的语言。
如果继续用python开发的话，适当使用asyncio对内存的开销应该会减少很多

**Comment by XiaoYouChR** [comment]
前几天在旅游，今天正在用asyncio和httpx优化下载模块，预计今天随着v3.3版本一起pull。打算使用纯Python开发，因为可扩展性强。

**Comment by XiaoYouChR** [comment]
自动分段功能用asynicio实现似乎有点困难？🤔

**Comment by XiaoYouChR** [comment]
将PySide6版本更新到6.6.2可以解决内存泄露的问题。
目前已经给下载引擎加上了client复用，占用大幅减小。
