### ISSUE TITLE
【建议】能不能加入其他系统的支持？

### ISSUE THREAD

**Issue by YHX2010** [XiaoYouChR/Ghost-Downloader-3#14]
如题，本人用 Mac（M2 Air），不支持 Win 程序…… :(

**Comment by XiaoYouChR** [comment]
v3.3.* 计划，需要等待移除win32api的引用

**Comment by YHX2010** [comment]
呃……移除Win32API支持后的话……我帮你编译？

**Comment by YHX2010** [comment]
我正好用着ARM的Mac，至于X86版Mac用GitHub Action/虚拟机应该OK

**Comment by XiaoYouChR** [comment]
目前已经移除win32api了，你可以尝试编译。或者你能帮我测试吗？我正在考虑使用Github Action帮我打包。有意的话加QQ群531928387

**Comment by YHX2010** [comment]
OK，我现在试试

**Comment by XiaoYouChR** [comment]
加QQ群吧 531928387 交流方便点 答案应该是 晓游ChR
