### ISSUE TITLE
[BUG]关于浏览器插件

### ISSUE THREAD

**Issue by CreeperAWA** [XiaoYouChR/Ghost-Downloader-3#21]
1. 浏览器插件不被Chrome信任，无法启用。

解压后加载已解压的拓展程序就行

这是浏览器的提示
![PixPin_2024-08-14_13-57-31](https://github.com/user-attachments/assets/a0edb83a-2d5a-415c-abfa-3da450db5739)

2. 有时候下载提示已取消，但并未开始

**Comment by XiaoYouChR** [comment]
第一点正在寻找相应的解决方案
第二点是因为浏览器插件和下载器断联后的第一次下载会尝试重新连接下载器，逻辑问题，亟待解决

**Comment by CreeperAWA** [comment]
> 第一点正在寻找相应的解决方案 第二点是因为浏览器插件和下载器断联后的第一次下载会尝试重新连接下载器，逻辑问题，亟待解决

第一点的解决方案似乎除了上架谷歌商店、冒充其他插件（绝对不可以这么做）、修改注册表（加白名单）以及用检查删除启/禁用控件的disable外没有其他办法，我的解决方案就是解压后用开发者模式加载，程序可以适当引导一下用户用开发者模式加载

**Comment by XiaoYouChR** [comment]
第二个问题 v3.4.1 已修复

**Comment by shiny6667** [comment]
开发者模式解压后添加

**Comment by CreeperAWA** [comment]
> 开发者模式解压后添加

感谢回复 我已经提到了
> 我的解决方案就是解压后用开发者模式加载

**Comment by XiaoYouChR** [comment]
![image](https://github.com/user-attachments/assets/7db7047d-0d53-4404-9234-67b5676421fc)
