### ISSUE TITLE
关于GUI

### ISSUE THREAD

**Issue by Ziyang-Bai** [XiaoYouChR/Ghost-Downloader-3#24]
提一些小建议
软件GUI加载速度欠佳，感觉可以用一些轻量的GUI库
图标有些不好看，也可以重新设计一个？
![downloader](https://github.com/user-attachments/assets/295011c9-fc3d-4264-b124-424655a4e830)
系统托盘图标位置不对 托盘图标没有按照预期在鼠标上出现，而且出现在了托盘图标折叠处
托盘图标模糊
不过这些都是可有可无的，不做也是Ok的

**Comment by XiaoYouChR** [comment]
软件GUI卡顿我这几天想了想，是线程创建和暂停的时候需要执行的操作太多了。是可以优化的
关于图标，用的是都是微软的FluentIcon，这点应该是萝卜青菜各有所爱吧😂
系统托盘是用的第三方库的问题，过几天我会给它提issue和自己的解决方案（其实没修# 之前还会有背景错位的问题）
托盘图标模糊是因为图标本来就太细了吧（？会考虑优化的，确实不好找，在暗色主题下

**Comment by hkdkfih** [comment]
其实可以用Windows原生的Winui(https://github.com/ynkdir/py-win32more 和 https://github.com/sotanakamura/winui-python)

**Comment by XiaoYouChR** [comment]
- GUI 反应速度已优化

**Comment by XiaoYouChR** [comment]
v3.4.1 已更改下载器 Logo，托盘已优化。
请更新下载器版本
