### ISSUE TITLE
一些关于GUI和系统下载功能的小建议

### ISSUE THREAD

**Issue by hkdkfih** [XiaoYouChR/Ghost-Downloader-3#26]
- ui可以用原生的Winui(https://github.com/sotanakamura/winui-python)
- 把系统下载做成一个独立的项目
- 搭建一个服务器让开发者把自己的系统上传
- 添加系统镜像烧录功能

**Comment by XiaoYouChR** [comment]
有实力自己开发

**Comment by XiaoYouChR** [comment]
源码都没看懂

**Comment by YHX2010** [comment]
> * ui可以用原生的Winui(https://github.com/sotanakamura/winui-python)
> * 把系统下载做成一个独立的项目
> * 搭建一个服务器让开发者把自己的系统上传
> * 添加系统镜像烧录功能

呵呵，理想很丰满

**Comment by YHX2010** [comment]
> 有实力请提交 Pull Request

赞成！x666
