### ISSUE TITLE
【浏览器插件】开启代理的时候可能出现报错异常

### ISSUE THREAD

**Issue by KDreamelf** [XiaoYouChR/Ghost-Downloader-3#38]
## 设备信息：
```
设备名称	DESKTOP-EFLOMUT
处理器	Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz   2.50 GHz
机带 RAM	16.0 GB
设备 ID	B5E63ED0-DFD0-43F1-A018-C1F6985E9641
产品 ID	00326-10000-00000-AA719
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
```
## 操作系统信息：
```
版本	Windows 10 家庭版
版本号	22H2
安装日期	‎2024/‎8/‎2
操作系统内部版本	19045.4842
体验	Windows Feature Experience Pack 1000.19060.1000.0
```
## 运行代理软件：
clash for windows（2022.11.25）（某个定制版，”关于“页面被清空了，所以只能看见内核版本。）
## 报错信息截图：
![QQ20240905-224751](https://github.com/user-attachments/assets/0304cf80-0d01-42fc-af7c-cbee0f1dbf7f)
![QQ20240905-224659](https://github.com/user-attachments/assets/f9483db2-1892-4443-bcfd-df7ab0066099)
---
由于无法使用浏览器插件接管下载，故只能暂时雪藏此神器。另外建议浏览器插件可以设置排除项什么的，防止在某些特定的网页风控跳下载并截断资源正常加载（IDM就有过这种问题，但可以去设置里排除）

**Comment by XiaoYouChR** [comment]
排除项的添加在计划之内
报错是本来就会有的情况，因为是在开发者模式安装的脚本，WebSocket会强制报错
至于无法连接至下载器，请问设置系统代理的时候是否排除了 Localhost ？

**Comment by KDreamelf** [comment]
点错了，不好意思

**Comment by XiaoYouChR** [comment]
请上传运行日志

**Comment by KDreamelf** [comment]
[Ghost Downloader 运行日志.log](https://github.com/user-attachments/files/17000781/Ghost.Downloader.log)
这几天都开着开机自启但是没有使用。

**Comment by XiaoYouChR** [comment]
日志内并未包含有效信息，但已找到解决方案。预计下一版本 `v3.3.7` 或 `v3.4.0` 修复

**Comment by XiaoYouChR** [comment]
v3.4.1 已修复，请更新下载器版本
