### ISSUE TITLE
浏览器插件捕获任务异常

### ISSUE THREAD

**Issue by jdjfjdsfj** [XiaoYouChR/Ghost-Downloader-3#39]
https://vw-entrynavi.autonavi.com/entrynavi/download/map_data?&brand=vw&project=entrynavi&channel=vw-entry&timestamp=1600083417686&signature_nonce=109509&signature=NGFiYWM5MDJlZDE5N2E5ZmEwYjAzODg5YjA3ZmFlZGVlMzE1MTk5NjFiMDE2ZWYxMWFjMDMwYTg4ZWQ1N2I4Yg%3D%3D&signature_method=HMAC-SHA256&signature_version=1.0  不知为何无法接管。扩展正常

**Comment by XiaoYouChR** [comment]
![QQ_1725596928479](https://github.com/user-attachments/assets/c636540d-8f66-41ed-8c4a-d03f9480af9b)

**Comment by XiaoYouChR** [comment]
正常接管并且成功下载

**Comment by jdjfjdsfj** [comment]
> 正常接管并且成功下载

主要是下载广东省地图这样的大文件，无法接管的会比较多

**Comment by jdjfjdsfj** [comment]
> 正常接管并且成功下载

且部分文件接管后，浏览器会突然弹出下载已取消

**Comment by XiaoYouChR** [comment]
亟待修复

**Comment by jdjfjdsfj** [comment]
> 亟待修复

作者加油，期待修复

**Comment by XiaoYouChR** [comment]
v3.4.1 已修复，请更新下载器版本
