### ISSUE TITLE
无法正常暂停下载任务

### ISSUE THREAD

**Issue by zha2024** [XiaoYouChR/Ghost-Downloader-3#42]
文件删不了，直接卡死
![image](https://github.com/user-attachments/assets/c854985c-b95a-444c-8b1d-26dc3a47716b)
把这个和原文件清空才管用
![image](https://github.com/user-attachments/assets/2662c03a-2b98-4df9-8217-2293b23355b5)

**Comment by XiaoYouChR** [comment]
开发版已修复，等待推送 v3.4.1

**Comment by XiaoYouChR** [comment]
https://github.com/XiaoYouChR/Ghost-Downloader-3/commit/a71530229b69663bf7b0541f3cfbb6b3341f550e

**Comment by XiaoYouChR** [comment]
v3.4.1 已修复，请更新下载器版本

**Comment by zha2024** [comment]
v3.4.1 还是不行
![image](https://github.com/user-attachments/assets/fd10a469-6e66-438d-9f36-068d92f80df4)

**Comment by zha2024** [comment]
有时候行

**Comment by XiaoYouChR** [comment]
我也遇到了，暂时切换至 v3.3.6 解决问题吧 😵

**Comment by XiaoYouChR** [comment]
已修复！请更新 v3.4.2
