### ISSUE TITLE
bug：无法更新到3.4.1

### ISSUE THREAD

**Issue by CuSO4with5H2O** [XiaoYouChR/Ghost-Downloader-3#46]
将3.4.1版本的程序文件，替换掉原目录3.4.0的程序文件，重新打开程序或重启电脑，进入后仍提示更新，且版本号仍显示3.4.0，但是新版本如修改程序图标等改动生效，直接解压新版本程序运行也是相同效果

**Comment by XiaoYouChR** [comment]
收假太匆忙，忘改版本号了，把检查更新关掉应急吧。周末只放6个小时😭

**Comment by CuSO4with5H2O** [comment]
啊这……

**Comment by CuSO4with5H2O** [comment]
啊这……
