### ISSUE TITLE
已经是最新版仍然提示更新

### ISSUE THREAD

**Issue by OnesoftQwQ** [XiaoYouChR/Ghost-Downloader-3#47]
如题，从Releases下载的3.4.1版本打开后提示更新3.4.1
![image](https://github.com/user-attachments/assets/e0a385c3-9132-408b-a07d-0806489f537a)

**Comment by OnesoftQwQ** [comment]
找到问题了，3.4.1程序里写的还是3.4.0

**Comment by XiaoYouChR** [comment]
#46
