### ISSUE TITLE
希望能开放下载任务接口

### ISSUE THREAD

**Issue by baiyao105** [XiaoYouChR/Ghost-Downloader-3#48]
- 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。 

**背景**
我正在开发一种烧入程序,需要使用多线程下载功能

**想要实现的功能**
因为不好理解代码(耗时),希望开发接口,使其可以更容易的调用(

**Comment by XiaoYouChR** [comment]
现在调用已经十分容易了，本身设计的时候就是考虑功能拆分的🤔🤔🤔
请参考 common/signal_bus.py 里面关于下载信号的连接情况和 component/task_card.py 对相关信号的处理

**Comment by baiyao105** [comment]
谢谢🍋
