### ISSUE TITLE
记忆窗口位置

### ISSUE THREAD

**Issue by lovegamerod** [XiaoYouChR/Ghost-Downloader-3#56]
在我的电脑上，Ghost Downloader会出现一些显示问题，比如在开机时会突然跳个弹窗出来（虽然我知道这是开机启动，但是有点影响观感），而且窗口会过大，在我1920x1080，缩放150%（默认）时，Ghost Downloader的最上方会超出显示范围，要我先改窗口的宽窄让窗口自动下来露出x，O，-，再去手动调整窗口大小，有点影响体验，希望能调整一下，如果要更多信息的话我可以补充

**Comment by XiaoYouChR** [comment]
打算是优化彻底静默开机启动和窗口大小记忆

**Comment by lovegamerod** [comment]
感觉还能改进的一个点是下载之前弹个弹窗（类似于IDM那种）并且下载完成后也能谈个弹窗出来附带打开文件/打开文件夹/关闭这种

**Comment by XiaoYouChR** [comment]
> 感觉还能改进的一个点是下载之前弹个弹窗（类似于IDM那种）并且下载完成后也能谈个弹窗出来附带打开文件/打开文件夹/关闭这种

#53

**Comment by lovegamerod** [comment]
所以下一次更新是啥时候捏，期待了

**Comment by lovegamerod** [comment]
不小心点到close了

**Comment by lovegamerod** [comment]
所以这一次更新加入这个功能了吗

**Comment by XiaoYouChR** [comment]
整不会了

**Comment by XiaoYouChR** [comment]
更新 v3.4.4 以修复
