### ISSUE TITLE
多线程下载文件缩水

### ISSUE THREAD

**Issue by Alan-QAQ** [XiaoYouChR/Ghost-Downloader-3#61]
我通过插件下载网盘内容时，它显示的大小是正确的，但是真正的文件不是正常大小，无法打开，线程开的越多，缩水越多
[Ghost Downloader 运行日志.log](https://github.com/user-attachments/files/17788278/Ghost.Downloader.log)
![PixPin_2024-11-17_07-51-12](https://github.com/user-attachments/assets/691d9890-af6c-4cd6-b1af-2f24acf591f0)
![PixPin_2024-11-17_07-50-09](https://github.com/user-attachments/assets/dc9d2b6c-b7ca-4f9a-a8e9-2fedf96cae41)

**Comment by XiaoYouChR** [comment]
通过日志分析出来问题之后试图修复了，不知道你更新 v3.4.3 之后会不会复现，我这里没有出现这种情况😵‍💫

**Comment by romantcig147** [comment]
更新后仍然出现问题，无法下载，下载后文件报错丢失，文件长时间不显示下载速度，文件出现400MB/s的下载错误

**Comment by XiaoYouChR** [comment]
请提供具体的工作环境、操作系统，还有具体的下载链接和程序日志。还有下载到的磁盘是 U 盘吗？谢谢！

**Comment by romantcig147** [comment]
> 请提供具体的工作环境、操作系统，还有具体的下载链接和程序日志。还有下载到的磁盘是 U 盘吗？谢谢！
电脑，windows10工作站版，下载链接已失效，运行日志，下载到的是机械硬盘非u盘和固态硬盘

[Ghost Downloader 运行日志.log](https://github.com/user-attachments/files/17879183/Ghost.Downloader.log)

**Comment by XiaoYouChR** [comment]
方法3获取文件名时没有做对应的 url 解码工作导致文件名不合法
* 修复方法3获取文件名时的问题
* 添加文件名不合法的校验，包括自动避开重复文件名、不合法的字符等

**Comment by Alan-QAQ** [comment]
本次下载到本地，问题仍然存在，已更新至最新版本，IDM可正常获取文件大小
![PixPin_2024-12-01_19-57-07](https://github.com/user-attachments/assets/bd704acf-f911-459e-b908-c1887601ca07)
![PixPin_2024-12-01_20-26-18](https://github.com/user-attachments/assets/78f561f4-eb2e-4b49-82d7-41b293139046)
![PixPin_2024-12-01_20-22-48](https://github.com/user-attachments/assets/160b9dcd-3dc2-46fd-8e9b-62fc54e46a56)

**Comment by XiaoYouChR** [comment]
现在看

**Comment by XiaoYouChR** [comment]
![image](https://github.com/user-attachments/assets/b59edb19-1f98-48d5-888d-9ad40c72cad4)
可是浏览器下载也是 7.62 GB 啊

**Comment by XiaoYouChR** [comment]
方便的话可以加QQ群交流吗? 531928387 答案是 晓游ChR

**Comment by Alan-QAQ** [comment]
感谢，问题解决了
