### ISSUE TITLE
祝高考顺利

### ISSUE THREAD

**Issue by lighter540923555** [XiaoYouChR/Ghost-Downloader-3#63]
建议您近期减少精力投入，待高考结束后再继续维护，为了项目的长期维护，一定要考一个理想的大学呀，很喜欢您的UI设计，高考加油！！！

**Comment by XiaoYouChR** [comment]
感谢！

**Comment by XiaoYouChR** [comment]
说真的，v3.4.3 就是我因为被语言霸凌导致成绩下降心情低迷回家休息时候更新出来的版本。没想到刚刚更新出来就收到了来自陌生人的高考祝福。真的深深被温暖到了！确实当下我的任务是高考最重要！
走自己的路，让别人说去吧
真的十分感谢这么一句鼓励！加油，只剩下198天了
