### ISSUE TITLE
报错，无法使用

### ISSUE THREAD

**Issue by nvidia256** [XiaoYouChR/Ghost-Downloader-3#64]
![屏幕截图 2024-11-22 101714](https://github.com/user-attachments/assets/09dcdcca-733f-47f3-bd7a-57be7ea696e2)
WIN11专业版

**Comment by XiaoYouChR** [comment]
检查 杀毒软件 或者安装 微软常用运行库

**Comment by nvidia256** [comment]
已换回WIN10，能用了
