### ISSUE TITLE
方法3获取文件名时没有做对应的 url 解码工作导致文件名不合法

### ISSUE THREAD

**Issue by XiaoYouChR** [XiaoYouChR/Ghost-Downloader-3#65]
更新后仍然出现问题，无法下载，下载后文件报错丢失，文件长时间不显示下载速度，文件出现400MB/s的下载错误

_Originally posted by @romantcig147 in https://github.com/XiaoYouChR/Ghost-Downloader-3/issues/61#issuecomment-2493496259_

**Comment by XiaoYouChR** [comment]
* 修复方法3获取文件名时的问题
* 添加文件名不合法的校验，包括自动避开重复文件名、不合法的字符等

**Comment by romantcig147** [comment]
有办法解决他吗？我出现了没有下载软件的名字所以无法下载，以及损坏的文件

**Comment by XiaoYouChR** [comment]
明天周末修复

**Comment by XiaoYouChR** [comment]
v3.4.4 已修复
