### ISSUE TITLE
文件下载问题

### ISSUE THREAD

**Issue by TomasthehearseXD** [XiaoYouChR/Ghost-Downloader-3#68]
小文件线程开太多会难以结束下载，大文件（以26GB文件举例）线程开20以上SSD会难以初始化，HDD会变龟速（几MB/s）
另外，在特殊情况下（例如服务器在国外），难以获得正确文件名，且如果无法获取文件名则始终无法开始下载，而Chrome浏览器没这些毛病（但是慢的离谱）
也许可以让用户选择文件名获取方案？

**Comment by XiaoYouChR** [comment]
发日志

**Comment by Alpha-Qian** [comment]
我之前看获取文件信息的代码时，注意到第一个获取文件信息的请求response.raise_for_status()后并没有捕获错误，也不会重试，不能获取获得正确文件名可能是这个导致的
<img width="547" alt="屏幕截图 2024-12-04 212707" src="https://github.com/user-attachments/assets/c60a09bf-e666-4de7-be9a-6e1a41c461d5">

让用户选择文件名获取方案没有必要

**Comment by XiaoYouChR** [comment]
> 可能是第一个获取文件信息的请求response.raise_for_status()后并没有捕获错误，也不会重试，不能获取获得正确文件名可能是这个导致的 <img alt="屏幕截图 2024-12-04 212707" width="547" src="https://private-user-images.githubusercontent.com/154665575/392403904-c60a09bf-e666-4de7-be9a-6e1a41c461d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODExOTgsIm5iZiI6MTczMzQ4MDg5OCwicGF0aCI6Ii8xNTQ2NjU1NzUvMzkyNDAzOTA0LWM2MGEwOWJmLWU2NjYtNGRlNy1iZTlhLTZlMWE0MWM0NjFkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxMDI4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDVjZTczMTZmNTVmZjBiNzczYWE5ZTNiZmZhN2NiNTU0MTBiMGMzZTI5NzgxMjljZWI0MzMwOTc5NTJkNTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lchbU1dE3hBF_jzF5pTIx5m5wBU8A1McZ0JtRBXzhg4">
> 
> 让用户选择文件名获取方案没有必要

在外部有捕获
