### ISSUE TITLE
你说得对，所以更新后新Bug来啦

### ISSUE THREAD

**Issue by lovegamerod** [XiaoYouChR/Ghost-Downloader-3#69]
在删除除配置文件和记录文件以外的文件后，更新后，有的时候打开应用窗口上面几个下载进程会挤在一起，无法点击到（如果再复现我会第一时间在Issue提交图片）

还有，说好的下载前的确认弹窗呢[贴吧_愤怒]

**Comment by XiaoYouChR** [comment]
因为是从 v3.4.2 更新上来的, 你把文件删完就行了

**Comment by XiaoYouChR** [comment]
下载前的确认弹窗 #9
