### ISSUE TITLE
界面严重问题

### ISSUE THREAD

**Issue by TomasthehearseXD** [XiaoYouChR/Ghost-Downloader-3#70]
最新版本（3.4.4）的所有界面都十分卡顿
浏览器插件捕获下载请求后 如果点击弹出的系统通知，任务列表就会不再刷新并且任务列表不再相应操作
且如果不点击，界面则大概率重叠
效果如下：
文字描述：多个条目混合重叠，有时有空行，有时会有条目卡在左上角
效果图（徒手制作）：
![image](https://github.com/user-attachments/assets/ae910910-ab78-4af8-8b56-c7965b8809bd)
上图是空行情况（点击捕获请求的通知后任务列表大概率卡在这个情况）
![image](https://github.com/user-attachments/assets/06ab7ea2-a5c2-4ec7-87a1-e58bdc6e4c6d)
上图是重叠情况（使用浏览器插件捕获请求会出现此情况）
![image](https://github.com/user-attachments/assets/5bf7993d-b76e-4193-bdf9-943a579f6a70)
上图是卡半情况（此情况只能打开最上方条目的文件，无法点击暂停、校验、打开文件位置和删除的按钮，因为按键可能被上方的其他按钮阻挡）

**Comment by TomasthehearseXD** [comment]
卡半情况已复现：
![image](https://github.com/user-attachments/assets/e7698718-6356-4706-92a2-eb170f3188d6)

**Comment by XiaoYouChR** [comment]
上游 ExpandLayout 的问题, 我只是尝试修复了 没想到还是不行 😵

**Comment by XiaoYouChR** [comment]
能不能发日志

**Comment by XiaoYouChR** [comment]
系上游问题

**Comment by zhiyiYo** [comment]
不能换成 QVBoxLayout 吗

**Comment by TomasthehearseXD** [comment]
大问题
临时解决后体验更甜蜜的恶心了
不光其他界面画面撕裂，任务列表还又卡又慢，而且任务列表的滚动速度和的反应时间也像依托答辩
录屏如下：

https://github.com/user-attachments/assets/fb0997d1-e031-4edc-95fc-bc62e22b98e5

**Comment by XiaoYouChR** [comment]
所以是临时解决，已经想到比较好的解决方案了，待会更新

**Comment by XiaoYouChR** [comment]
界面操作延迟的问题已经解决了, 可是界面还是卡卡的

**Comment by XiaoYouChR** [comment]
v3.4.5已解决
