### ISSUE TITLE
下载无法查看大小的文件

### ISSUE THREAD

**Issue by XTY64XTY12345** [XiaoYouChR/Ghost-Downloader-3#72]
如Github直接下载压缩包

IDM：

![image](https://github.com/user-attachments/assets/31497137-dd37-4859-b080-aad56d504cf8)

Ghost-Downloader：

![image](https://github.com/user-attachments/assets/1af716b2-09f4-4d9b-8bfd-80868d1dbc9d)

虽然显示下载完毕，但实际上并没有下载

![image](https://github.com/user-attachments/assets/0a9797af-64b4-4f93-b9af-22169cd2f430)

![image](https://github.com/user-attachments/assets/b337bdd4-0eaf-4592-8ff4-64680dd75ff2)

**Comment by XiaoYouChR** [comment]
更新最新版本...
