### ISSUE TITLE
文件下载及校验值问题

### ISSUE THREAD

**Issue by TomasthehearseXD** [XiaoYouChR/Ghost-Downloader-3#74]
在3.4.4版本中，下载的文件与源文件的校验值不一样
影响非常大（尤其是在下载压缩包或手机系统镜像的时候）
如下是最近一次留有日志的文件，下载好的文件打不开，这里使用了256线程
日志文件：
[Ghost Downloader 运行日志.log](https://github.com/user-attachments/files/18135712/Ghost.Downloader.log)

**Comment by XiaoYouChR** [comment]
线程数过大，触发了网站的反攻击功能，不是逻辑问题

**Comment by XiaoYouChR** [comment]
为调整线程功能添加了警告⚠️
