### ISSUE TITLE
Edge无法使用浏览器扩展

### ISSUE THREAD

**Issue by chenxin0397** [XiaoYouChR/Ghost-Downloader-3#75]
我导出CRX文件，装到浏览器之后，无法启用该功能
![image](https://github.com/user-attachments/assets/a805893a-3c07-4203-a62f-6a26c84e28ae)

**Comment by XiaoYouChR** [comment]
你觉得安装插件的帮助按钮在下面是干什么用的😵‍💫

**Comment by chenxin0397** [comment]
> 你觉得安装插件的帮助按钮在下面是干什么用的😵‍💫

下图是我照安装插件的帮助按钮操作之后的结果
![image](https://github.com/user-attachments/assets/50721daa-42f2-46cd-b330-5c17b5b58f5d)
![image](https://github.com/user-attachments/assets/740d39c8-3520-4541-adcf-6de348543916)
